version: 1.2
workflows:
  - name: align_and_count_multiple_report
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/align_and_count_multiple_report.wdl
  - name: align_and_count
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/align_and_count.wdl
  - name: align_and_plot
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/align_and_plot.wdl
    testParameterFiles:
    - /test/input/WDL/test_inputs-align_and_plot-local.json
  - name: assemble_denovo
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/assemble_denovo.wdl
    testParameterFiles:
    - /test/input/WDL/test_inputs-assemble_denovo-local.json
  - name: assemble_denovo_metagenomic
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/assemble_denovo_metagenomic.wdl
  - name: assemble_refbased
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/assemble_refbased.wdl
    testParameterFiles:
    - /test/input/WDL/test_inputs-assemble_refbased-local.json
  - name: augur_export_only
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/augur_export_only.wdl
  - name: augur_from_assemblies
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/augur_from_assemblies.wdl
    testParameterFiles:
      - /test/input/WDL/test_inputs-augur_from_assemblies-local.json
  - name: augur_from_beast_mcc
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/augur_from_beast_mcc.wdl
    testParameterFiles:
      - /test/input/WDL/test_inputs-augur_from_beast_mcc-local.json
  - name: augur_from_mltree
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/augur_from_mltree.wdl
  - name: augur_from_msa
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/augur_from_msa.wdl
  - name: augur_from_msa_with_subsampler
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/augur_from_msa_with_subsampler.wdl
  - name: bams_multiqc
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/bams_multiqc.wdl
  - name: beast_gpu
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/beast_gpu.wdl
  - name: blastoff
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/blastoff.wdl
  - name: chunk_blast
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/megablast_chunk.wdl
  - name: classify_kaiju
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/classify_kaiju.wdl
  - name: classify_kraken2
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/classify_kraken2.wdl
    testParameterFiles:
    - /test/input/WDL/test_inputs-classify_kraken2-local.json
  - name: classify_krakenuniq
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/classify_krakenuniq.wdl
  - name: classify_multi
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/classify_multi.wdl
  - name: classify_single
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/classify_single.wdl
  - name: coverage_table
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/coverage_table.wdl
  - name: create_enterics_qc_viz
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/create_enterics_qc_viz.wdl
  - name: create_enterics_qc_viz_general
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/create_enterics_qc_viz_general.wdl
  - name: demux_only
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/demux_only.wdl
  - name: demux_deplete
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/demux_deplete.wdl
  - name: demux_metadata_only
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/demux_metadata_only.wdl
  - name: demux_plus
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/demux_plus.wdl
  - name: deplete_only
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/deplete_only.wdl
  - name: detect_cross_contamination
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/detect_cross_contamination.wdl
    testParameterFiles:
  - name: detect_cross_contamination_precalled_vcfs
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/detect_cross_contamination_precalled_vcfs.wdl
  - name: diff_genome_sets
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/diff_genome_sets.wdl
  - name: downsample
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/downsample.wdl
  - name: dump_gcloud_env_info
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/dump_gcloud_env_info.wdl
  - name: fastq_to_ubam
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/fastq_to_ubam.wdl
    testParameterFiles:
    - /test/input/WDL/test_inputs-fastq_to_ubam-local.json
  - name: fetch_annotations
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/fetch_annotations.wdl
  - name: fetch_sra_to_bam
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/fetch_sra_to_bam.wdl
  - name: filter_classified_bam_to_taxa
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/filter_classified_bam_to_taxa.wdl
  - name: filter_sequences
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/filter_sequences.wdl
  - name: genbank_gather
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/genbank_gather.wdl
  - name: genbank_single
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/genbank_single.wdl
    testParameterFiles:
    - /test/input/WDL/test_inputs-genbank_single-local.json
  - name: isnvs_merge_to_vcf
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/isnvs_merge_to_vcf.wdl
  - name: isnvs_lofreq
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/isnvs_lofreq.wdl
  - name: isnvs_one_sample
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/isnvs_one_sample.wdl
  - name: kraken2_build
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/kraken2_build.wdl
  - name: mafft_and_snp
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/mafft_and_snp.wdl
  - name: mafft_and_snp_annotated
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/mafft_and_snp_annotated.wdl
  - name: mafft_and_trim
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/mafft_and_trim.wdl
  - name: mafft
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/mafft.wdl
  - name: merge_bams
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/merge_bams.wdl
  - name: merge_metagenomics
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/merge_metagenomics.wdl
  - name: merge_tar_chunks
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/merge_tar_chunks.wdl
  - name: merge_vcfs_and_annotate
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/merge_vcfs_and_annotate.wdl
  - name: merge_vcfs
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/merge_vcfs.wdl
  - name: metagenomic_denovo
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/metagenomic_denovo.wdl
  - name: multiqc_only
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/multiqc_only.wdl
  - name: nextclade_single
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/nextclade_single.wdl
  - name: populate_library_and_sample_tables_from_flowcell
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/populate_library_and_sample_tables_from_flowcell.wdl
  - name: reconstruct_from_alignments
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/reconstruct_from_alignments.wdl
  - name: sarscov2_batch_relineage
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_batch_relineage.wdl
  - name: sarscov2_biosample_load
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_biosample_load.wdl
  - name: sarscov2_data_release
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_data_release.wdl
  - name: sarscov2_genbank
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_genbank.wdl
  - name: sarscov2_genbank_ingest
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_genbank_ingest.wdl
  - name: sarscov2_illumina_full
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_illumina_full.wdl
  - name: sarscov2_lineages
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_lineages.wdl
    testParameterFiles:
    - /test/input/WDL/test_inputs-sarscov2_lineages-local.json
  - name: calc_bam_read_depths
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/calc_bam_read_depths.wdl
  - name: sarscov2_gisaid_ingest
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_gisaid_ingest.wdl
  - name: sarscov2_nextclade_multi
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_nextclade_multi.wdl
  - name: sarscov2_nextstrain
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_nextstrain.wdl
  - name: sarscov2_nextstrain_aligned_input
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_nextstrain_aligned_input.wdl
  - name: sarscov2_sequencing_reports
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_sequencing_reports.wdl
  - name: sarscov2_sra_to_genbank
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/sarscov2_sra_to_genbank.wdl
  - name: scaffold_and_refine
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/scaffold_and_refine.wdl
  - name: scaffold_and_refine_multitaxa
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/scaffold_and_refine_multitaxa.wdl
  - name: simulate_illumina_reads
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/simulate_illumina_reads.wdl
    testParameterFiles:
    - /test/input/WDL/miniwdl-local/test_inputs-simulate_illumina_reads-local.json
  - name: submit_biosample
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/submit_biosample.wdl
  - name: submit_genbank
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/submit_genbank.wdl
  - name: submit_sra
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/submit_sra.wdl
  - name: subsample_by_casecounts
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/subsample_by_casecounts.wdl
  - name: subsample_by_metadata
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/subsample_by_metadata.wdl
  - name: subsample_by_metadata_with_focal
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/subsample_by_metadata_with_focal.wdl
  - name: terra_table_to_tsv
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/terra_table_to_tsv.wdl
  - name: terra_tsv_to_table
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/terra_tsv_to_table.wdl
  - name: terra_update_assemblies
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/terra_update_assemblies.wdl
  - name: trimal
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/trimal.wdl
  - name: classify_qiime2_multi
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/classify_qiime2_multi.wdl
  - name: qiime_import_bam
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/bam_to_qiime.wdl
  - name: unpack_archive_to_bucket
    subclass: WDL
    primaryDescriptorPath: /pipes/WDL/workflows/unpack_archive_to_bucket.wdl
